import Image from "next/image";
import Link from "next/link";
import { getGuestGuideContent } from "@/data/repository";

const toParagraphs = (text: string) => text.split(/\n\s*\n/).filter(Boolean).map((paragraph) => <p key={paragraph}>{paragraph}</p>);

export const dynamic = "force-dynamic";

export default async function GuestInfoPage() {
  const guide = await getGuestGuideContent();
  return <main className="guest-guide guest-guide-vivid">
    <header className="guest-guide-hero"><Image src="/images/quiet-2br-old-town-apartment.jpg" alt="The apartment kitchen and dining area" fill priority sizes="100vw" /><div><Link href="/" className="guest-guide-brand">HAVELSKÁ · PRAGUE OLD TOWN</Link><h1>{guide.title}</h1><p>{guide.subtitle}</p></div></header>
    <div className="guest-guide-content">
      <section id="welcome" className="guide-intro guide-intro-vivid"><span className="landing-kicker">Your Prague base</span><h2>Make yourself at home</h2>{toParagraphs(guide.welcome)}</section>
      <section id="arrival" className="guide-feature guide-feature-arrival"><div className="guide-feature-icon">✦</div><div><span className="landing-kicker">01 · Arrival</span><h2>Getting to the apartment</h2>{toParagraphs(guide.arrival)}<div className="guide-links"><a href="https://pidlitacka.cz/en" target="_blank" rel="noreferrer">Plan public transport ↗</a><a href="https://www.uber.com/" target="_blank" rel="noreferrer">Uber ↗</a><a href="https://bolt.eu/" target="_blank" rel="noreferrer">Bolt ↗</a></div></div></section>
      <section className="guide-feature guide-feature-keys"><div className="guide-feature-icon">⌂</div><div><span className="landing-kicker">02 · Check-in</span><h2>Keys & arrival time</h2>{toParagraphs(guide.keys)}</div></section>
      <section id="home" className="guide-section guide-section-home"><span className="guide-number">03</span><div><h2>Useful things at home</h2><div className="guide-grid guide-grid-vivid"><article className="guide-wifi"><span>⌁</span><h3>Wi-Fi</h3><p><strong>{guide.wifiName}</strong><br />Password: <strong>{guide.wifiPassword}</strong></p></article><article><span>♡</span><h3>Care for the flat</h3>{toParagraphs(guide.apartmentCare)}</article><article><span>☼</span><h3>Heating, water & power</h3>{toParagraphs(guide.utilities)}</article><article><span>♲</span><h3>Waste & recycling</h3>{toParagraphs(guide.recycling)}</article><article className="guide-wide"><span>☕</span><h3>Coffee, laundry & appliances</h3>{toParagraphs(guide.appliances)}</article></div><section className="technical-gallery" aria-labelledby="technical-gallery-title"><div><span className="landing-kicker">Emergency reference</span><h3 id="technical-gallery-title">Water, gas & electricity</h3><p>Please contact us first whenever possible. These photos are here to identify the right place quickly in an emergency.</p></div><div className="technical-photo-grid"><figure className="technical-water-access"><Image src="/images/guide/water-access.jpg" alt="Access point to the water shut-off under the kitchen cabinet" width={3024} height={4032}/><figcaption><strong>Water shut-off</strong><span>Behind the framed access area under the kitchen cabinet.</span></figcaption></figure><figure><Image src="/images/guide/water-meter.jpg" alt="Water meter detail" width={4032} height={3024}/><figcaption><strong>Water meter</strong><span>The meter confirms you are at the water shut-off.</span></figcaption></figure><figure><Image src="/images/guide/gas-shutoff.jpg" alt="Yellow gas shut-off valve" width={3024} height={4032}/><figcaption><strong>Gas shut-off</strong><span>The yellow valve in the kitchen cabinet.</span></figcaption></figure><figure className="technical-electrical"><Image src="/images/guide/electrical-cabinets.jpg" alt="Electrical cabinets in the corridor" width={3024} height={4032}/><Image src="/images/guide/main-breaker.jpg" alt="Main electrical breaker inside the cabinet" width={3024} height={4032}/><figcaption><strong>Main breaker</strong><span>Open the middle electrical cabinet, then use the marked breaker inside.</span></figcaption></figure></div></section></div></section>
      <section id="prague" className="guide-feature guide-feature-prague"><div className="guide-feature-icon">♥</div><div><span className="landing-kicker">04 · Out & about</span><h2>A few Prague favourites</h2>{toParagraphs(guide.pragueTips)}<div className="prague-photo-pair"><figure><Image src="/images/guide/prague-day.jpg" alt="View across Prague from a hilltop" width={1920} height={1440}/><figcaption>A bright Prague afternoon</figcaption></figure><figure><Image src="/images/guide/prague-sunset.jpg" alt="Sunset over Prague and Prague Castle" width={1920} height={1440}/><figcaption>Sunset near Prague Castle</figcaption></figure></div><div className="place-list"><a href="https://maps.app.goo.gl/m4YtsmRPWmEbyEZY6" target="_blank" rel="noreferrer"><span className="place-logo place-logo-koruna" aria-hidden="true">HK</span><span className="place-copy"><strong>Havelská Koruna</strong><span>Czech classics nearby ↗</span></span></a><a href="https://maps.app.goo.gl/cZ7xjVCi4a5e5Xea8" target="_blank" rel="noreferrer"><span className="place-logo place-logo-louvre" aria-hidden="true">L</span><span className="place-copy"><strong>Café Louvre</strong><span>Breakfast & coffee ↗</span></span></a><a href="https://maps.app.goo.gl/4XWuSbYDQmD6xfZK6" target="_blank" rel="noreferrer"><span className="place-logo place-logo-lidl" aria-hidden="true">Lidl</span><span className="place-copy"><strong>Lidl</strong><span>Everyday groceries ↗</span></span></a><a href="https://maps.app.goo.gl/ZzjYGHc14cSZh2mB8" target="_blank" rel="noreferrer"><span className="place-logo place-logo-tesco" aria-hidden="true">Tesco</span><span className="place-copy"><strong>Tesco</strong><span>Late grocery option ↗</span></span></a></div></div></section>
      <section id="checkout" className="guide-feature guide-feature-checkout"><div className="guide-feature-icon">✓</div><div><span className="landing-kicker">05 · Departure</span><h2>Before you leave</h2>{toParagraphs(guide.checkout)}</div></section>
      <section id="help" className="guide-help"><span className="landing-kicker">Need assistance?</span><h2>We&apos;re here to help.</h2>{toParagraphs(guide.help)}</section>
    </div>
  </main>;
}
